circlepattern_dims:
  cols: 2
  data: [7, 3]
  rows: 1
blobdetector_min_area: 15
blobdetector_min_dist_between_blobs: 2
distance_between_centers: 0.0125
publish_circles: True
bottom_crop: 1
top_crop: 1
